MODULES_FOLDER = "modules/"
TEMPLATES_FOLDER = "templates/"
EXTRA_INCLUDES_FOLDER = "extraIncludes/"

RENDER_BASE = f"{TEMPLATES_FOLDER}RenderBase.cpp"
BEAM_RAY_MARCH_TEMPLATE = f"{TEMPLATES_FOLDER}BeamRayMarch-M_Beam.cpp"

FUNCTIONS_PLACEHOLDER = "//%_FUNCTIONS_%"
CALL_EXTERNAL_FUNCTIONS_PLACEHOLDER = "/*%_CALL_%*/"

STRUCT_WRAPPER_CODE = f"struct CP_FunctionsWrapper \\{ {FUNCTIONS_PLACEHOLDER} }; CP_FunctionsWrapper cpfw;"
EXTERNAL_FUNCTIONS_PREPEND = "cpfw."